# Generated by Django 4.2.1 on 2023-08-31 13:22

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_librarian_member_delete_account'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('subject', models.CharField(max_length=127)),
                ('page_counts', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='books', to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Borrowed'), ('R', 'Reserved'), ('L', 'Lost')], max_length=1)),
                ('publication_date', models.DateField()),
                ('barcode', models.CharField(max_length=15, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('book_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.bookitem')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('borrowed_book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.borrowedbook')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)])),
                ('book_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.bookitem')),
                ('reserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
